### ISSUE TITLE
taro 隐私组件 怎么调用父页面的方法

### ISSUE THREAD

**Issue by shamohai** [hsuna/taro-privacy-popup#1]
代码写的太好了，就是这个隐私组件 点击同意的时候，我想调用父页面的一个函数，重新加载父页面的数据。我把这个父页面的函数当成隐私组件的属性赋值，隐私组件点击的时候调用父组件的函数，这个父页面函数里有this调用，就会报错。通过调试发现this指向是这个隐私组件本身，我刚接触taro，不是很熟，大神能否指点一二，谢谢。

**Comment by hsuna** [comment]
传入的函数，可以在传入前使用箭头函数包裹，确保作用域依然是父页面

**Comment by shamohai** [comment]
> 传入的函数，可以在传入前使用箭头函数包裹，确保作用域依然是父页面

非常感激，解决了我一大难题啊。

**Comment by abramyangfab** [comment]
我在 "A" tabbar页面调用了隐私组件，点击拒绝，然后switchTab到"B"tabbar页面，再回到”A“ tabbar页面继续调用，弹窗就不显示了，然后再switchTab到"B"，弹窗显示在“B”页面。
