### ISSUE TITLE
在多个tabbar页面同时打开问题

### ISSUE THREAD

**Issue by abramyangfab** [hsuna/taro-privacy-popup#2]
我在 "A" tabbar页面调用了隐私组件，点击拒绝，然后switchTab到"B"tabbar页面，再回到”A“ tabbar页面继续调用，弹窗就不显示了，然后再switchTab到"B"，弹窗显示在“B”页面。

**Comment by abramyangfab** [comment]
在最新的版本中，应该保留useEffect当中的逻辑，否则非tabbar页面的弹窗会停留在tabbar上面

**Comment by hsuna** [comment]
主要原因是onNeedPrivacyAuthorization的触发时，onDisShow还没回调，最新版本将覆盖和弹窗判定推迟到onDisShow之后。
