### ISSUE TITLE
点击弹窗的同意没反应

### ISSUE THREAD

**Issue by Jeijie** [hsuna/taro-privacy-popup#3]
为什么我点击弹窗的同意没反应，是哪里我漏了或者不对吗？

已经安装"@tarojs/plugin-inject": "^3.6.16"，也加了下面的配置，但是就是发现同意按钮的handleAgree方法没有执行到
### config/index.js:

`plugins: [
      [
        '@tarojs/plugin-html',
        '@tarojs/plugin-inject',
        {
          // 配置需要新增的 API
          syncApis: [
            'getPrivacySetting',
            'openPrivacyContract',
            'requirePrivacyAuthorize',
            'onNeedPrivacyAuthorization',
            'onAgreePrivacyAuthorization'
          ],
          components: {
            // 配置组件新增 属性和事件
            Button: {
              bindAgreePrivacyAuthorization: '',
            },
          },
        },
      ],
  ]
`

**Comment by hsuna** [comment]
Taro 3.3+ 请使用 1.0 以上版本
Taro 3.1/3.2 请使用 0.0.2 版本

检查下Taro的版本

**Comment by Jeijie** [comment]
Taro v3.6.8，对应@tarojs/plugin-inject":3.6.16版本不对吗
👽 Taro v3.6.8


  Taro CLI 3.6.8 environment info:
    System:
      OS: macOS 13.3.1
      Shell: 5.9 - /bin/zsh
    Binaries:
      Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
      Yarn: 1.22.10 - /usr/local/bin/yarn
      npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
    npmPackages:
      @tarojs/cli: ^3.6.9-alpha.13 => 3.6.13 
      @tarojs/components: 3.6.8 => 3.6.8 
      @tarojs/mini-runner: 3.6.8 => 3.6.8 
      @tarojs/plugin-framework-react: 3.6.8 => 3.6.8 
      @tarojs/plugin-html: ^3.6.8 => 3.6.8 
      @tarojs/react: 3.6.8 => 3.6.8 
      @tarojs/runtime: 3.6.8 => 3.6.8 
      @tarojs/taro: 3.6.8 => 3.6.8 
      @tarojs/webpack-runner: 3.6.8 => 3.6.8 
      babel-preset-taro: 3.6.8 => 3.6.8 
      eslint-config-taro: 3.6.8 => 3.6.8 
      react: ^17.0.0 => 17.0.2

**Comment by hsuna** [comment]
试下和Taro同版本的inject，3.3+版本后，版本是一对一的

**Comment by Jeijie** [comment]
我升级到最新版本可以了，但是现在又点击同意包报另外的问题了

`getPhoneNumber:fail privacy permission is not authorized or buttonId is wrong,errno:104`

**Comment by hsuna** [comment]
看下管理后台隐私政策是否没有设置好，需要在提审步骤那开启隐私条款，并加入所需要获取的权限，比如手机号，位置，剪贴板等等（可以看下openPrivacyContract内的隐私政策是否没有手机号这一项，需要新增才行）。

**Comment by Jeijie** [comment]
应该设置好了的，我尝试换了其他权限也会报错，或者换了另外的小程序appId还是有这个错
`"errMsg":"getClipboardData:fail privacy permission is not authorized or buttonId is wrong","errno":104`

**Comment by hsuna** [comment]
https://github.com/hsuna/taro-privacy-popup/pull/11
