### ISSUE TITLE
多次切换tabbar底部按钮，点击 同意 时 隐私窗口不会隐藏

### ISSUE THREAD

**Issue by shamohai** [hsuna/taro-privacy-popup#4]
tabbar底部有4个按钮菜单，每个tabbar 页面都加了隐私组件，隐私窗口由于不能覆盖底部的tabbar, 在多次切换tabbar菜单页面后，再点击某个页面的隐私窗口 同意 按钮， 隐私窗口不会消失隐藏。

**Comment by hsuna** [comment]
是最新的版本吗？

**Comment by shamohai** [comment]
是最新版本

**Comment by shamohai** [comment]
我重新下载最新版本代码，来回切换未出现所描述的问题，我再看看我的代码吧，看看有什么不同之处。多切换几次，demo有个error “getLocation:fail privacy permission is not authorized or buttonId is wrong”

**Comment by hsuna** [comment]
https://github.com/hsuna/taro-privacy-popup/pull/11

**Comment by hsuna** [comment]
https://github.com/hsuna/taro-privacy-popup/pull/11
